{% set name = "cutest" %}
{% set version = "1.5" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://sourceforge.net/projects/cutest/files/cutest/{{ version }}/cutest-{{ version }}.zip
  sha256: 279e1f20c33396c644a5647579dd4b23cd67b8f10bffdcb7cfebec85b4567705

build:
  number: 0
  run_exports:
    - {{ pin_subpackage(name, max_pin="x") }}

requirements:
  build:
    - {{ compiler('c') }}

test:
  source_files:
    - AllTests.c
    - CuTestTest.c
  requires:
    - {{ compiler('c') }}

about:
  home: https://cutest.sourceforge.net
  license: zlib-acknowledgement
  license_file: license.txt
  summary: 'A unit testing library for the C language'

extra:
  recipe-maintainers:
    - twrightsman
